  - name: "installing python"
    shell: "yum install python3 -y"

  - name: "Repository"
    yum_repository:
       name: "Docker"
       description: "Docker Repo"
       baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
       gpgcheck: "no"
  -  name: "creating docker package"
     package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

  -  name: "service starting"
     service:
       name: "docker"
       state: started
       enabled: yes

  -  name: "Installing python"
     command: "pip3 install docker"



- hosts: ["tag_Name_master"]
  roles:
  - name: "Configuring Master Node"
    role:  "./Master"

- hosts: ["tag_Name_slave1", "tag_Name_slave2"]
  vars_prompt:
  - name: "master_token"
    prompt: "Enter Token To Join To Master: "
    private: no
  roles:
  - name: "Configuring Slave Node"
    role:  "./Slaves"

- hosts: ["tag_Name_master"]
  roles:
  - name: "Launching Wordpress and Mysql"
    role: "./wordpress-mysql"
